# ==============================================================================
# == 手動觸發 yfinance 診斷測試 (manual_test_yfinance.yml)
# ==============================================================================
# 說明：
# 這個 GitHub Action 工作流程允許您從 GitHub 網站上手動觸發，
# 來執行 test_yfinance.py 腳本。
# 主要目的：
# 1. 建立一個乾淨的 Python 執行環境。
# 2. 安裝最新版的 yfinance 套件及其他必要函式庫。
# 3. 執行診斷腳本，並在 Action 的執行紀錄中顯示詳細的輸出結果。
# ==============================================================================

name: "手動診斷 yfinance 功能"

on:
  # workflow_dispatch 允許你從 GitHub 網站的 "Actions" 頁面手動觸發此工作流程
  workflow_dispatch:

jobs:
  diagnose-yfinance:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虛擬機來執行
    
    steps:
      # 第一步：將你的程式碼從 GitHub 倉庫下載到虛擬機中
      - name: "Checkout 專案程式碼"
        uses: actions/checkout@v4

      # 第二步：設定 Python 環境
      - name: "設定 Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 第三步：安裝 Python 套件
      - name: "安裝 yfinance 及其他相依套件"
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance # 強制升級 yfinance 到最新版
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # 第四步：執行我們的診斷腳本
      - name: "執行 test_yfinance.py 腳本"
        run: python test_yfinance.py
