name: Update Stock Prices

on:
  workflow_dispatch:        # 允許手動執行
  schedule:
    - cron: '30 5 * * *'     # 13:30 UTC+8 執行
    - cron: '0 14 * * *'     # 06:00 UTC+8 執行
    - cron: '0,10,20,30,40,50 1,2,3 * * 1,2,3,4,5'     # 美股開盤前三小時每10分鐘更新一次

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests pandas

      - name: Run price-update script
        env:
          D1_WORKER_URL: ${{ secrets.D1_WORKER_URL }}
          D1_API_KEY: ${{ secrets.D1_API_KEY }}
          GCP_API_URL: ${{ secrets.GCP_API_URL }}
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: python main.py
