name: Update Stock Prices

on:
  workflow_dispatch:        # 允許手動執行
  schedule:
    - cron: '0 2 * * *'     # 每日 00:00 UTC 執行

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests pandas

      - name: Run price-update script
        env:
          D1_WORKER_URL: ${{ secrets.D1_WORKER_URL }}
          D1_API_KEY: ${{ secrets.D1_API_KEY }}
          GCP_API_URL: ${{ secrets.GCP_API_URL }}
        run: python main.py
